`timescale 1ns/1ps
module EHXPLLJ #(
 parameter PLLRST_ENA=0, INTFB_WAKE=0, STDBY_ENABLE=0, DPHASE_SOURCE=0,
 parameter CLKOP_FPHASE=0, CLKOP_CPHASE=0, OUTDIVIDER_MUXA2=0, CLKOP_ENABLE=0,
 parameter CLKOP_DIV=8, CLKFB_DIV=8, CLKI_DIV=1, FEEDBK_PATH=0
)(
 input CLKI, CLKFB, RST, RESETM, RESETC, RESETD, PHASESEL0, PHASESEL1, PHASEDIR, PHASESTEP,
 LOADREG, STDBY, PLLWAKESYNC, ENCLKOP,
 output CLKOP, LOCK, CLKINTFB
);
reg clk = 0;
always #7.8125 clk = ~clk;
assign CLKOP = clk;
assign CLKINTFB = clk;
assign LOCK = 1;
endmodule

